/**
 * Foundational Rules — built-in merchant patterns that ship with the app.
 *
 * ARCHITECTURE:
 *   - The rule LOGIC lives here in code (patterns, names, emojis, descriptions).
 *   - The per-account USER STATE (enabled flag + category mapping) lives in
 *     the `foundational_rule_settings` DB table (see queries.ts).
 *   - The engine merges these at runtime via getActiveFoundationalRulesAsRules().
 *
 * ORDERING CONTRACT:
 *   User rules always run BEFORE foundational rules. The engine appends foundational
 *   rules at the END of the merged array. applyRulesToTransactions is first-match-wins,
 *   so a user rule always wins when both would match the same transaction.
 */

import type { RuleCondition } from '../db/queries';

export interface FoundationalRule {
  id:                  string;           // stable key, e.g. "food-dining"
  name:                string;           // "Food & Dining"
  emoji:               string;           // "🍔"
  description:         string;           // "Restaurants, takeout, coffee, fast food"
  defaultCategoryName: string;           // matches the starter category name for auto-mapping
  conditions:          RuleCondition[];  // all OR'd together — see logic field
  logic:               'OR';            // always OR; one match is enough
}

export const FOUNDATIONAL_RULES: FoundationalRule[] = [
  {
    id: 'food-dining',
    name: 'Food & Dining',
    emoji: '🍔',
    description: 'Restaurants, takeout, coffee, fast food',
    defaultCategoryName: 'Food & Dining',
    logic: 'OR',
    conditions: [
      // Fast food
      { match_type: 'contains', match_text: 'mcdonald' },
      { match_type: 'contains', match_text: 'burger king' },
      { match_type: 'contains', match_text: 'wendy' },
      { match_type: 'contains', match_text: 'chick-fil-a' },
      { match_type: 'contains', match_text: 'taco bell' },
      { match_type: 'contains', match_text: 'chipotle' },
      { match_type: 'contains', match_text: 'subway' },
      { match_type: 'contains', match_text: 'panera' },
      { match_type: 'contains', match_text: 'five guys' },
      { match_type: 'contains', match_text: 'shake shack' },
      { match_type: 'contains', match_text: 'in-n-out' },
      { match_type: 'contains', match_text: 'whataburger' },
      { match_type: 'contains', match_text: 'raising cane' },
      { match_type: 'contains', match_text: 'wingstop' },
      { match_type: 'contains', match_text: 'popeye' },
      { match_type: 'contains', match_text: 'panda express' },
      { match_type: 'contains', match_text: 'jack in the box' },
      { match_type: 'contains', match_text: 'dairy queen' },
      { match_type: 'contains', match_text: 'sonic drive' },
      { match_type: 'contains', match_text: 'jersey mike' },
      { match_type: 'contains', match_text: 'jimmy john' },
      { match_type: 'contains', match_text: 'qdoba' },
      { match_type: 'contains', match_text: 'moe\'s southwest' },
      { match_type: 'contains', match_text: 'habit burger' },
      // Pizza
      { match_type: 'contains', match_text: 'pizza hut' },
      { match_type: 'contains', match_text: 'papa john' },
      { match_type: 'contains', match_text: 'domino' },
      { match_type: 'contains', match_text: 'little caesar' },
      { match_type: 'contains', match_text: 'papa murphy' },
      { match_type: 'contains', match_text: 'mod pizza' },
      { match_type: 'contains', match_text: 'blaze pizza' },
      // Coffee
      { match_type: 'contains', match_text: 'starbucks' },
      { match_type: 'contains', match_text: 'dunkin' },
      { match_type: 'contains', match_text: 'dutch bros' },
      { match_type: 'contains', match_text: 'peet\'s coffee' },
      { match_type: 'contains', match_text: 'caribou coffee' },
      { match_type: 'contains', match_text: 'coffee bean' },
      { match_type: 'contains', match_text: 'tim horton' },
      // Sit-down chains
      { match_type: 'contains', match_text: 'chili\'s' },
      { match_type: 'contains', match_text: 'applebee' },
      { match_type: 'contains', match_text: 'olive garden' },
      { match_type: 'contains', match_text: 'outback' },
      { match_type: 'contains', match_text: 'texas roadhouse' },
      { match_type: 'contains', match_text: 'red lobster' },
      { match_type: 'contains', match_text: 'longhorn steakhouse' },
      { match_type: 'contains', match_text: 'ihop' },
      { match_type: 'contains', match_text: 'dennys' },
      { match_type: 'contains', match_text: 'denny\'s' },
      { match_type: 'contains', match_text: 'waffle house' },
      { match_type: 'contains', match_text: 'cracker barrel' },
      { match_type: 'contains', match_text: 'buffalo wild wings' },
      { match_type: 'contains', match_text: 'cheesecake factory' },
      { match_type: 'contains', match_text: 'red robin' },
      { match_type: 'contains', match_text: 'sweetgreen' },
      { match_type: 'contains', match_text: 'noodles & company' },
      // Additional national chains
      { match_type: 'contains', match_text: 'kfc' },
      { match_type: 'contains', match_text: 'culver' },
      { match_type: 'contains', match_text: 'el pollo loco' },
      { match_type: 'contains', match_text: 'del taco' },
      { match_type: 'contains', match_text: 'arby' },
      { match_type: 'contains', match_text: 'hardee' },
      { match_type: 'contains', match_text: 'carl\'s jr' },
      { match_type: 'contains', match_text: 'church\'s chicken' },
      { match_type: 'contains', match_text: 'bojangle' },
      { match_type: 'contains', match_text: 'zaxby' },
      { match_type: 'contains', match_text: 'crumbl' },
      { match_type: 'contains', match_text: 'cinnabon' },
      { match_type: 'contains', match_text: 'auntie anne' },
      { match_type: 'contains', match_text: 'jamba juice' },
      { match_type: 'contains', match_text: 'smoothie king' },
      { match_type: 'contains', match_text: 'tropical smoothie' },
      { match_type: 'contains', match_text: 'firehouse subs' },
      { match_type: 'contains', match_text: 'potbelly' },
      { match_type: 'contains', match_text: 'boston market' },
      { match_type: 'contains', match_text: 'freebirds' },
      { match_type: 'contains', match_text: 'mister softee' },
      // Food delivery apps
      { match_type: 'contains', match_text: 'doordash' },
      { match_type: 'contains', match_text: 'uber eats' },
      { match_type: 'contains', match_text: 'grubhub' },
      { match_type: 'contains', match_text: 'seamless' },
      { match_type: 'contains', match_text: 'postmates' },
      { match_type: 'contains', match_text: 'caviar' },
      // Restaurant-specific POS prefix (Toast — restaurant industry only)
      { match_type: 'contains', match_text: 'tst*' },
      // Generic food lexicon — broad nouns that almost always indicate a
      // restaurant, café, bakery, etc. Each was vetted against real backup
      // data with FP=0; intentionally excluded: `deli` (collides with
      // "delivery"), `kitchen` (collides with cookware/home goods),
      // `bar` (too short, hits "barber" etc.).
      { match_type: 'contains', match_text: 'cafe' },
      { match_type: 'contains', match_text: 'coffee' },
      { match_type: 'contains', match_text: 'bakery' },
      { match_type: 'contains', match_text: 'bagel' },
      { match_type: 'contains', match_text: 'pizza' },
      { match_type: 'contains', match_text: 'taqueria' },
      { match_type: 'contains', match_text: 'bistro' },
      { match_type: 'contains', match_text: 'diner' },
      { match_type: 'contains', match_text: 'tavern' },
      { match_type: 'contains', match_text: 'grill' },
      { match_type: 'contains', match_text: 'bbq' },
      { match_type: 'contains', match_text: 'donut' },
      { match_type: 'contains', match_text: 'brewing' },
      { match_type: 'contains', match_text: 'creamery' },
      { match_type: 'contains', match_text: 'ice cream' },
      { match_type: 'contains', match_text: 'restaurant' },
      { match_type: 'contains', match_text: 'eatery' },
      { match_type: 'contains', match_text: 'sushi' },
      { match_type: 'contains', match_text: 'ramen' },
      { match_type: 'contains', match_text: 'pho ' },         // trailing space — avoid matching "phoenix", "phosphate"
      { match_type: 'contains', match_text: 'noodle' },
      { match_type: 'contains', match_text: 'trattoria' },
      { match_type: 'contains', match_text: 'patisserie' },
      { match_type: 'contains', match_text: 'gelato' },
      { match_type: 'contains', match_text: 'boba' },
      { match_type: 'contains', match_text: 'smoothie' },
      { match_type: 'contains', match_text: 'cuisine' },
      { match_type: 'contains', match_text: 'barbecue' },
      { match_type: 'contains', match_text: 'bowls' },         // catches "açaí bowls", "BACKYARD BOWLS"; "bowls" (with s) avoids "bowling" collision
      { match_type: 'contains', match_text: 'restaura' },      // catches truncated "CHINESE RESTAURA..." forms common in 22-char descriptors
      { match_type: 'contains', match_text: 'too good to go' },
    ],
  },

  {
    id: 'groceries',
    name: 'Groceries',
    emoji: '🛒',
    description: 'Supermarkets, grocery stores, and grocery delivery',
    defaultCategoryName: 'Groceries',
    logic: 'OR',
    conditions: [
      { match_type: 'contains', match_text: 'kroger' },
      { match_type: 'contains', match_text: 'safeway' },
      { match_type: 'contains', match_text: 'trader joe' },
      { match_type: 'contains', match_text: 'whole foods' },
      { match_type: 'contains', match_text: 'publix' },
      { match_type: 'contains', match_text: 'heb ' },
      { match_type: 'contains', match_text: 'h-e-b' },
      { match_type: 'contains', match_text: 'wegman' },
      { match_type: 'contains', match_text: 'giant food' },
      { match_type: 'contains', match_text: 'stop & shop' },
      { match_type: 'contains', match_text: 'food lion' },
      { match_type: 'contains', match_text: 'winn-dixie' },
      { match_type: 'contains', match_text: 'winndixie' },
      { match_type: 'contains', match_text: 'aldi' },
      { match_type: 'contains', match_text: 'sprouts' },
      { match_type: 'contains', match_text: 'fresh market' },
      { match_type: 'contains', match_text: 'market basket' },
      { match_type: 'contains', match_text: 'meijer' },
      { match_type: 'contains', match_text: 'harris teeter' },
      { match_type: 'contains', match_text: 'natural grocers' },
      { match_type: 'contains', match_text: 'stater bros' },
      { match_type: 'contains', match_text: 'lucky supermarket' },
      { match_type: 'contains', match_text: 'fry\'s food' },
      { match_type: 'contains', match_text: 'king soopers' },
      { match_type: 'contains', match_text: 'vons' },
      { match_type: 'contains', match_text: 'ralphs' },
      { match_type: 'contains', match_text: 'smith\'s food' },
      { match_type: 'contains', match_text: 'fred meyer' },
      { match_type: 'contains', match_text: 'giant eagle' },
      { match_type: 'contains', match_text: 'price chopper' },
      { match_type: 'contains', match_text: 'brookshire' },
      { match_type: 'contains', match_text: 'piggly wiggly' },
      { match_type: 'contains', match_text: 'bi-lo' },
      { match_type: 'contains', match_text: 'food 4 less' },
      { match_type: 'contains', match_text: 'save-a-lot' },
      { match_type: 'contains', match_text: 'lidl' },
      // Grocery delivery
      { match_type: 'contains', match_text: 'instacart' },
      { match_type: 'contains', match_text: 'shipt' },
      { match_type: 'contains', match_text: 'amazon fresh' },
      { match_type: 'contains', match_text: 'freshly' },
    ],
  },

  {
    id: 'transportation',
    name: 'Transportation',
    emoji: '🚗',
    description: 'Gas stations, rideshare, transit, and parking',
    defaultCategoryName: 'Transportation',
    logic: 'OR',
    conditions: [
      // Gas stations
      { match_type: 'contains', match_text: 'shell' },
      { match_type: 'contains', match_text: 'chevron' },
      { match_type: 'contains', match_text: 'exxon' },
      { match_type: 'contains', match_text: 'mobil' },
      { match_type: 'contains', match_text: 'bp ' },
      { match_type: 'contains', match_text: 'valero' },
      { match_type: 'contains', match_text: 'marathon' },
      { match_type: 'contains', match_text: 'sunoco' },
      { match_type: 'contains', match_text: 'circle k' },
      { match_type: 'contains', match_text: 'speedway' },
      { match_type: 'contains', match_text: 'quiktrip' },
      { match_type: 'contains', match_text: 'wawa' },
      { match_type: 'contains', match_text: 'racetrac' },
      { match_type: 'contains', match_text: 'pilot flying' },
      { match_type: 'contains', match_text: 'love\'s travel' },
      { match_type: 'contains', match_text: 'phillips 66' },
      { match_type: 'contains', match_text: 'conoco' },
      { match_type: 'contains', match_text: 'arco' },
      { match_type: 'contains', match_text: 'murphy usa' },
      { match_type: 'contains', match_text: 'murphy express' },
      { match_type: 'contains', match_text: 'casey\'s general' },
      { match_type: 'contains', match_text: 'gate petroleum' },
      { match_type: 'contains', match_text: 'sheetz' },
      // Rideshare
      { match_type: 'contains', match_text: 'uber' },
      { match_type: 'contains', match_text: 'lyft' },
      { match_type: 'contains', match_text: 'waymo' },
      // Transit
      { match_type: 'contains', match_text: 'mta ' },
      { match_type: 'contains', match_text: 'bart ' },
      { match_type: 'contains', match_text: 'cta ' },
      { match_type: 'contains', match_text: 'metro transit' },
      { match_type: 'contains', match_text: 'metra' },
      { match_type: 'contains', match_text: 'amtrak' },
      { match_type: 'contains', match_text: 'greyhound' },
      { match_type: 'contains', match_text: 'megabus' },
      { match_type: 'contains', match_text: 'e-zpass' },
      { match_type: 'contains', match_text: 'sunpass' },
      { match_type: 'contains', match_text: 'fastrak' },
      { match_type: 'contains', match_text: 'parking' },
      { match_type: 'contains', match_text: 'spothero' },
      { match_type: 'contains', match_text: 'parkwhiz' },
    ],
  },

  {
    id: 'entertainment',
    name: 'Entertainment',
    emoji: '🎬',
    description: 'Streaming, movies, music, and events',
    defaultCategoryName: 'Entertainment',
    logic: 'OR',
    conditions: [
      // Streaming
      { match_type: 'contains', match_text: 'netflix' },
      { match_type: 'contains', match_text: 'hulu' },
      { match_type: 'contains', match_text: 'disney plus' },
      { match_type: 'contains', match_text: 'disney+' },
      { match_type: 'contains', match_text: 'hbo max' },
      { match_type: 'contains', match_text: 'hbo now' },
      { match_type: 'contains', match_text: 'max.com' },
      { match_type: 'contains', match_text: 'peacock' },
      { match_type: 'contains', match_text: 'paramount+' },
      { match_type: 'contains', match_text: 'paramount plus' },
      { match_type: 'contains', match_text: 'discovery+' },
      { match_type: 'contains', match_text: 'apple tv' },
      { match_type: 'contains', match_text: 'amazon prime video' },
      { match_type: 'contains', match_text: 'prime video' },
      { match_type: 'contains', match_text: 'fubo' },
      { match_type: 'contains', match_text: 'sling tv' },
      { match_type: 'contains', match_text: 'youtube premium' },
      { match_type: 'contains', match_text: 'youtube tv' },
      // Music
      { match_type: 'contains', match_text: 'spotify' },
      { match_type: 'contains', match_text: 'apple music' },
      { match_type: 'contains', match_text: 'tidal' },
      { match_type: 'contains', match_text: 'pandora' },
      { match_type: 'contains', match_text: 'sirius xm' },
      { match_type: 'contains', match_text: 'siriusxm' },
      // Movies & events
      { match_type: 'contains', match_text: 'amc theatres' },
      { match_type: 'contains', match_text: 'regal cinemas' },
      { match_type: 'contains', match_text: 'cinemark' },
      { match_type: 'contains', match_text: 'fandango' },
      { match_type: 'contains', match_text: 'ticketmaster' },
      { match_type: 'contains', match_text: 'stubhub' },
      { match_type: 'contains', match_text: 'eventbrite' },
      // Gaming
      { match_type: 'contains', match_text: 'xbox game pass' },
      { match_type: 'contains', match_text: 'playstation plus' },
      { match_type: 'contains', match_text: 'nintendo' },
      { match_type: 'contains', match_text: 'steam games' },
    ],
  },

  {
    id: 'shopping',
    name: 'Shopping',
    emoji: '🛍️',
    description: 'Online and retail purchases',
    defaultCategoryName: 'Shopping',
    logic: 'OR',
    conditions: [
      { match_type: 'contains', match_text: 'amazon' },
      { match_type: 'contains', match_text: 'walmart' },
      { match_type: 'contains', match_text: 'target' },
      { match_type: 'contains', match_text: 'best buy' },
      { match_type: 'contains', match_text: 'home depot' },
      { match_type: 'contains', match_text: 'lowe\'s' },
      { match_type: 'contains', match_text: 'lowes' },
      { match_type: 'contains', match_text: 'costco' },
      { match_type: 'contains', match_text: 'sam\'s club' },
      { match_type: 'contains', match_text: 'bj\'s wholesale' },
      { match_type: 'contains', match_text: 'ikea' },
      { match_type: 'contains', match_text: 'wayfair' },
      { match_type: 'contains', match_text: 'chewy' },
      { match_type: 'contains', match_text: 'ebay' },
      { match_type: 'contains', match_text: 'etsy' },
      { match_type: 'contains', match_text: 'nordstrom' },
      { match_type: 'contains', match_text: 'macy\'s' },
      { match_type: 'contains', match_text: 'macys' },
      { match_type: 'contains', match_text: 'kohls' },
      { match_type: 'contains', match_text: 'kohl\'s' },
      { match_type: 'contains', match_text: 'jcpenney' },
      { match_type: 'contains', match_text: 'sears' },
      { match_type: 'contains', match_text: 'old navy' },
      { match_type: 'contains', match_text: 'gap store' },
      { match_type: 'contains', match_text: 'banana republic' },
      { match_type: 'contains', match_text: 'h&m' },
      { match_type: 'contains', match_text: 'zara' },
      { match_type: 'contains', match_text: 'uniqlo' },
      { match_type: 'contains', match_text: 'tj maxx' },
      { match_type: 'contains', match_text: 't.j. maxx' },
      { match_type: 'contains', match_text: 'marshalls' },
      { match_type: 'contains', match_text: 'ross stores' },
      { match_type: 'contains', match_text: 'burlington' },
      { match_type: 'contains', match_text: 'dollar tree' },
      { match_type: 'contains', match_text: 'dollar general' },
      { match_type: 'contains', match_text: 'five below' },
      { match_type: 'contains', match_text: 'menards' },
      { match_type: 'contains', match_text: 'ace hardware' },
      { match_type: 'contains', match_text: 'michaels store' },
      { match_type: 'contains', match_text: 'hobby lobby' },
      { match_type: 'contains', match_text: 'joann fabric' },
      { match_type: 'contains', match_text: 'petco' },
      { match_type: 'contains', match_text: 'petsmart' },
      { match_type: 'contains', match_text: 'bath & body' },
      { match_type: 'contains', match_text: 'victoria\'s secret' },
      { match_type: 'contains', match_text: 'vs pink' },
      { match_type: 'contains', match_text: 'nike' },
      { match_type: 'contains', match_text: 'adidas' },
      { match_type: 'contains', match_text: 'apple store' },
      { match_type: 'contains', match_text: 'apple.com' },
      { match_type: 'contains', match_text: 'microsoft store' },
    ],
  },

  {
    id: 'health',
    name: 'Health',
    emoji: '💊',
    description: 'Pharmacy, doctor, gym, and insurance',
    defaultCategoryName: 'Health',
    logic: 'OR',
    conditions: [
      // Pharmacies
      { match_type: 'contains', match_text: 'cvs pharmacy' },
      { match_type: 'contains', match_text: 'cvs/pharmacy' },
      { match_type: 'contains', match_text: 'walgreen' },
      { match_type: 'contains', match_text: 'rite aid' },
      { match_type: 'contains', match_text: 'duane reade' },
      { match_type: 'contains', match_text: 'express scripts' },
      { match_type: 'contains', match_text: 'caremark' },
      { match_type: 'contains', match_text: 'optumrx' },
      { match_type: 'contains', match_text: 'goodrx' },
      { match_type: 'contains', match_text: 'amazon pharmacy' },
      // Gyms
      { match_type: 'contains', match_text: 'planet fitness' },
      { match_type: 'contains', match_text: 'la fitness' },
      { match_type: 'contains', match_text: 'anytime fitness' },
      { match_type: 'contains', match_text: '24 hour fitness' },
      { match_type: 'contains', match_text: 'gold\'s gym' },
      { match_type: 'contains', match_text: 'golds gym' },
      { match_type: 'contains', match_text: 'equinox' },
      { match_type: 'contains', match_text: 'crunch fitness' },
      { match_type: 'contains', match_text: 'ymca' },
      { match_type: 'contains', match_text: 'classpass' },
      { match_type: 'contains', match_text: 'peloton' },
      { match_type: 'contains', match_text: 'lifetime fitness' },
      { match_type: 'contains', match_text: 'orangetheory' },
      { match_type: 'contains', match_text: 'f45 training' },
      { match_type: 'contains', match_text: 'soulcycle' },
      { match_type: 'contains', match_text: 'barry\'s bootcamp' },
      // Health insurance & misc
      { match_type: 'contains', match_text: 'kaiser permanente' },
      { match_type: 'contains', match_text: 'blue cross' },
      { match_type: 'contains', match_text: 'bluecross' },
      { match_type: 'contains', match_text: 'aetna' },
      { match_type: 'contains', match_text: 'cigna' },
      { match_type: 'contains', match_text: 'unitedhealth' },
      { match_type: 'contains', match_text: 'anthem' },
      { match_type: 'contains', match_text: 'humana' },
      { match_type: 'contains', match_text: 'doctor' },
      { match_type: 'contains', match_text: 'urgent care' },
    ],
  },
];
